version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.desktop
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
