version: '3.8'

services:
  app:
    # appディレクトリのDockerfileを使ってビルド
    build: ./app
    # コンテナ名を固定して、ホストからアクセスしやすくする
    container_name: test-power
    restart: unless-stopped
    # シグナルを正しく処理するために `init` を有効化 (重要)
    init: true
