# NVIDIAの公式CUDAイメージをベースにする
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

# 対話形式のプロンプトを無効化
ENV DEBIAN_FRONTEND=noninteractive

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Ultralyticsライブラリをインストール
RUN pip3 install ultralytics

# デーモンスクリプトをコピー
COPY grpc-server.py /grpc-server.py
RUN chmod +x /grpc-server.py

CMD ["/grpc-server.py"]
