# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mode-controll.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mode-controll.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mode-controll.proto\"\x1b\n\x0bModeRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\"\x1f\n\x0cModeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32:\n\x0eModeController\x12(\n\x07SetMode\x12\x0c.ModeRequest\x1a\r.ModeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mode_controll_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEREQUEST']._serialized_start=23
  _globals['_MODEREQUEST']._serialized_end=50
  _globals['_MODERESPONSE']._serialized_start=52
  _globals['_MODERESPONSE']._serialized_end=83
  _globals['_MODECONTROLLER']._serialized_start=85
  _globals['_MODECONTROLLER']._serialized_end=143
# @@protoc_insertion_point(module_scope)
